package com.example.khabar.core.utils

import com.example.khabar.data.model.Country

object CountryHelper {
    val countries = listOf(
        Country("AR", "Argentina", "🇦🇷"),
        Country("AU", "Australia", "🇦🇺"),
        Country("AT", "Austria", "🇦🇹"),
        Country("BE", "Belgium", "🇧🇪"),
        Country("BR", "Brazil", "🇧🇷"),
        Country("BG", "Bulgaria", "🇧🇬"),
        Country("CA", "Canada", "🇨🇦"),
        Country("CN", "China", "🇨🇳"),
        Country("CO", "Colombia", "🇨🇴"),
        Country("CU", "Cuba", "🇨🇺"),
        Country("CZ", "Czech Republic", "🇨🇿"),
        Country("EG", "Egypt", "🇪🇬"),
        Country("FR", "France", "🇫🇷"),
        Country("DE", "Germany", "🇩🇪"),
        Country("GR", "Greece", "🇬🇷"),
        Country("HK", "Hong Kong", "🇭🇰"),
        Country("HU", "Hungary", "🇭🇺"),
        Country("IN", "India", "🇮🇳"),
        Country("ID", "Indonesia", "🇮🇩"),
        Country("IE", "Ireland", "🇮🇪"),
        Country("IL", "Israel", "🇮🇱"),
        Country("IT", "Italy", "🇮🇹"),
        Country("JP", "Japan", "🇯🇵"),
        Country("LV", "Latvia", "🇱🇻"),
        Country("LT", "Lithuania", "🇱🇹"),
        Country("MY", "Malaysia", "🇲🇾"),
        Country("MA", "Morocco", "🇲🇦"),
        Country("MX", "Mexico", "🇲🇽"),
        Country("NL", "Netherlands", "🇳🇱"),
        Country("NZ", "New Zealand", "🇳🇿"),
        Country("NG", "Nigeria", "🇳🇬"),
        Country("NO", "Norway", "🇳🇴"),
        Country("PH", "Philippines", "🇵🇭"),
        Country("PL", "Poland", "🇵🇱"),
        Country("PT", "Portugal", "🇵🇹"),
        Country("RO", "Romania", "🇷🇴"),
        Country("RU", "Russia", "🇷🇺"),
        Country("SA", "Saudi Arabia", "🇸🇦"),
        Country("RS", "Serbia", "🇷🇸"),
        Country("SG", "Singapore", "🇸🇬"),
        Country("SK", "Slovakia", "🇸🇰"),
        Country("SI", "Slovenia", "🇸🇮"),
        Country("ZA", "South Africa", "🇿🇦"),
        Country("KR", "South Korea", "🇰🇷"),
        Country("ES", "Spain", "🇪🇸"),
        Country("SE", "Sweden", "🇸🇪"),
        Country("CH", "Switzerland", "🇨🇭"),
        Country("TW", "Taiwan", "🇹🇼"),
        Country("TH", "Thailand", "🇹🇭"),
        Country("TR", "Turkey", "🇹🇷"),
        Country("UA", "Ukraine", "🇺🇦"),
        Country("AE", "United Arab Emirates", "🇦🇪"),
        Country("GB", "United Kingdom", "🇬🇧"),
        Country("US", "United States", "🇺🇸"),
        Country("VE", "Venezuela", "🇻🇪")
    )
}